apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-test
 labels:
  app: api-test
spec:
 replicas: 1
 selector:
  matchLabels:
   app: api-test
 template:
  metadata:
   labels:
    app: api-test
   annotations:
    ves.io/wingman-injection-mode: disable
  spec:
   containers:
    - name: api-test
      image: harbor-portal.daisuke.mydistributed.cloud/dnakajima/api-server:1.1
      ports:
      - containerPort: 8080
    - name: svc-client
      image: harbor-portal.daisuke.mydistributed.cloud/library/netutils:1.5

---

   
apiVersion: v1
kind: Service
metadata:
 name: api-test 
spec:
 type: ClusterIP
 ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8080
 selector:
  app: api-test
